trigger:
- none

pool:
  name: Self-Hosted

stages:
  - stage: 'POC'
    variables:
    - template: ${{variables['System.DefaultWorkingDirectory']}}/variables/infra.yml

    jobs:
    - deployment: 'Deploy'
      environment: 'POC'
      strategy:
        runOnce:
          deploy:
            steps:

              #build image from dockerfile
              - task: Docker@2
                inputs:
                  containerRegistry: ${{variables.acrConnection}}
                  repository: $(var_acrName)
                  command: 'build'
                  Dockerfile: 'https://github.com/migonel/containersProject/blob/master/dockerfile'
                displayName: 'Docker image build'

              #push image to ACR
              - task: Docker@2
                inputs:
                  containerRegistry: ${{variables.acrConnection}}
                  repository: $(var_acrName)
                  command: 'push'
                displayName: 'Docker image push'