trigger:
- none

pool:
  name: Self-Hosted

stages:
  - stage: 'POC'
    variables:
    - template: ${{variables['System.DefaultWorkingDirectory']}}/variables/infra.yml

    jobs:
    - deployment: 'Build'
      environment: 'POC'
      strategy:
        runOnce:
          deploy:
            steps:

              - checkout: self
                submodules: true

              #build image from dockerfile
              - task: Docker@2
                inputs:
                  containerRegistry: ${{variables.acrConnection}}
                  repository: 'djangoImage'
                  command: 'build'
                  Dockerfile: $(Build.SourcesDirectory)/dockerfile
                displayName: 'Docker image build'

              #push image to ACR
              - task: Docker@2
                inputs:
                  containerRegistry: ${{variables.acrConnection}}
                  repository: 'djangoImage'
                  command: 'push'
                displayName: 'Docker image push'