trigger:
- none

pool:
  name: Self-Hosted

stages:
  - stage: 'POC'
    variables:
    - template: ${{variables['System.DefaultWorkingDirectory']}}/variables/infra.yml

    jobs:
    - deployment: 'Deploy'
      environment: 'POC'
      strategy:
        runOnce:
          deploy:
            steps:

              - checkout: self
                submodules: true

              - task: AzureWebAppContainer@1
                displayName: 'Azure Web App on Container Deploy: $(WebApp.Name)'
                inputs:
                    azureSubscription: '$(Azure.ServiceConnectionId)'
                    appName: $(WebApp.Name)
                    imageName: '$(ACR.FullName)/$(ACR.ImageName)'