trigger:
- none

pool:
  name: Self-Hosted

stages:
  - stage: 'POC'
    variables:
    - template: ${{variables['System.DefaultWorkingDirectory']}}/variables/infra.yml

    jobs:
    - deployment: 'Deploy'
      environment: 'POC'
      strategy:
        runOnce:
          deploy:
            steps:
              
              # #Deploy Resource Group
              # - template: ${{variables['System.DefaultWorkingDirectory']}}/infra/templates/resource-group.yml
              #   parameters:
              #     azureConnection: ${{variables.azureConnection}}
              #     resourceGroupName: $(var_resourceGroupName)
              #     location: $(var_location)
              
                            #Deploy Resource Group
              # - template: ${{variables['System.DefaultWorkingDirectory']}}/infra/templates/azure-container-registry.yml
              #   parameters:
              #     azureConnection: ${{variables.azureConnection}}
              #     resourceGroupName: $(var_resourceGroupName)
              #     location: $(var_location)
              #     acrName: $(var_acrName)
              #     acrSKU: $(var_acrSKU)

              #Deploy App Service Plan Free tier 
              - template: ${{variables['System.DefaultWorkingDirectory']}}/infra/templates/app-service-plan.yml
                parameters:
                  azureConnection: ${{variables.azureConnection}}
                  resourceGroupName: $(var_resourceGroupName)
                  location: $(var_location)
                  aspName: $(var_aspName)
                  aspSKU: $(var_aspSKU)
              


              #Deploy Web App for Containers
              - template: ${{variables['System.DefaultWorkingDirectory']}}/infra/templates/web-app.yml
                parameters:
                  azureConnection: ${{variables.azureConnection}}
                  resourceGroupName: $(var_resourceGroupName)
                  location: $(var_location)
                  aspName: $(var_aspName)
                  webappName: $(var_webappName)
                  containerImageName: $(var_containerImageName)