trigger:
- none

stages:
  - stage: 'POC'
    variables:
    - template: ${{variables['System.DefaultWorkingDirectory']}}/variables/infra.yml

    jobs:
    - deployment: 'DeployInfra'
      environment: 'POC'
      strategy:
        runOnce:
          deploy:
            steps:
              
              #Deploy Resource Group
              - template: ${{variables['System.DefaultWorkingDirectory']}}/infra/templates/resource-group.yml
                parameters:
                  azureConnection: $(azureConnection)
                  resourceGroupName: $(var_resourceGroupName)
                  location: $(var_location)