steps:
  - task: AzureCLI@2
    displayName: 'Deploy Resource Group'
    inputs:
      azureSubscription: '${{parameters.azureConnection}}'
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $resourceGroupName = '{{parameters.resourceGroupName}}'
        $location = '{{parameters.location}}'

        Write Host "ResourceGroupName: $resourceGroupName"
        Write Host "Location: $location"

        New-AzResourceGroup --Name $resourceGroupName --Location $location